$script = <<SCRIPT
sudo apt-get update
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt-get update
apt-cache policy docker-engine
sudo apt-get install -y docker-engine
sudo usermod -aG docker $(whoami)

curl --remote-name https://raw.githubusercontent.com/praqma-training/code-infra/jenkinsdocker/containers/jenkinsdocker/start.sh
chmod u+x ./start.sh
./start.sh
SCRIPT


Vagrant.configure(2) do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.define "Jenkins Server", primary: true do |server|
  
  server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = "Vagrant"
      provider.token = 'ce75aca163f9350375df71afb157303546fa4bab5ccc9729c838e965280be20d'
      provider.image = 'ubuntu-16-04-x64'
      provider.region = 'fra1'
      provider.size = '512mb'
      provider.privatenetworking = true
  end
  
  
	server.vm.hostname = "webserver"
  end
  # config.vm.provision "shell", inline: $script
  config.vm.provision "shell", path: "provision.sh"

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 9090
  # enable this to share remote access with others
  # config.vm.network "public_network"

end
