# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #
  config.vm.define "Artifatory", primary: true do |server|

    server.vm.provider :digital_ocean do |provider|
      provider.ssh_key_name = "MSI"
      provider.token = "545c3be8e21a770324cfd817926101fc6847ad54cc36913a1b202c6c17beb52f"
      provider.image = 'ubuntu-16-04-x64'
      provider.region = 'fra1'
      provider.size = '512mb'
      provider.privatenetworking = true
    end

    server.vm.hostname = "Artifactory"
    server.vm.provision "shell", inline: <<-SHELL
	  sudo apt-get update
      adduser builder
	  usermod -aG sudo builder
	  
	  su - builder | mkdir ~/.ssh
	  su - builder | chmod 700 ~/.ssh
	  su - builder | echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7DzLVB3BW4vlGumn7RSzNW0eEy9q2hU5hhbxPzcJvG4TfhnAZcCKzlNgJcEP9EMF/RTTQmLBh6EF73AyEP+Rh8dR3MDzRR6RkjAfc+r1ldk5c3x/UOfG7Gr8dw9cKxVmqVE9bMdRzrnozZTKB0nLggBilE62mZZrC2vrtJjhgiaVu26HYZwGt/707EpRCqBHZsJBIX5+pB0rIbJ1OOd2bO/NqJnAe7u1GtK2I+a0cu6uBrdQqUJcF4vYOpKSfwVrAl7mLUD/Qn37G8NU938XgaxR0E+XIodkfF4rmIqv6CjiTvo77msMLLbfCfMnxLRmxJ6ke+HowALPRMzvVgyNUrlNuytfbBOwDKxSlQgHseGxeS+tHchT5OmexWO5yvD2RISSoAe/UMef+q39EZ/+wqr1Cr4jjNVNx6UqiKa42VJpPd3+bb+0lSTr4QBTmXW/3SREHC83WqjrT6EvwltFVyrNoiDSs7+/jydCu/K7or11dyvOM31lPaqBowoRaQSSsEA22NjTuf9LMUeQ7WlTmdv7auoRrT1L9VV09rsZ+kwRA14pJilVDcnZTu5bZVuOg7Xi1Q+bsFYlpzo4FexascTQzsBA3MIXBF/36v9WQ4pu+eBQASAsS4m872NbNRglj3V80MdH3gix+/ZWzBX1p/WbXJmuny7YO8pKz3S1RWQ== Animcuil@gmail.com"> ~/.ssh/authorized_keys
	  su - builder | chmod 600 ~/.ssh/authorized_keys
	  su - builder | wget https://raw.githubusercontent.com/datsoftlyngby/soft2017fall-lsd-teaching-material/master/lecture_notes/05-Code_Infrastructure/remote/setup.sh
	  su - builder | chmod u+x ./setup.sh
	  su - builder | ./setup.sh
	  
    SHELL
  end
  
	
end
