version: '3'
services:
  server:
    image: goserver
    ports:
      - "8081:8081"
  client:
    image: goclient
    links: 
    - server
  client1:
    image: goclient
    links: 
    - server
  client2:
    image: goclient
    links: 
    - server
  client3:
    image: goclient
    links: 
    - server

    